######################################################################
# Automatically generated by qmake (2.01a) lun. mai 23 16:35:46 2016
######################################################################

TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Vecteur3N.h Vecteur3.h
SOURCES += Vecteur3N.cpp Vecteur3NMain.cpp Vecteur3.cpp
